class Laptop
{
    String Model;
    int price;

    public String toString()
    {
        return Model + " : " +price;

    }

     // Generated by IDE
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((Model == null) ? 0 : Model.hashCode());
        result = prime * result + price;
        return result;
    }

    // Generated by IDE

    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Laptop other = (Laptop) obj;
        if (Model == null) {
            if (other.Model != null)
                return false;
        } else if (!Model.equals(other.Model))
            return false;
        if (price != other.price)
            return false;
        return true;
    }

    
}

public class object_Class{
    public static void main(String[] args) {
    
        Laptop obj = new Laptop();

        obj.Model = "Vostro 3574";
        obj.price = 45000;

        Laptop obj2 = new Laptop();

        obj2.Model = "Vostro 3574";
        obj2.price = 45000;

        boolean result = obj.equals(obj2);
        
        System.out.println(result);  
        
     //   System.out.println(obj);    // by default it calling toString();
    }
}
